"""add phone no in user table

Revision ID: 964bdd91e511
Revises: 68f5ad6f9a7e
Create Date: 2022-08-14 17:21:06.438231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964bdd91e511'
down_revision = '68f5ad6f9a7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_no')
    # ### end Alembic commands ###
